/* checklists.c — CJ2 emergency checklist data (see checklists.h) */
#include "checklists.h"

const char *UNIVERSAL_ADVANCE[] = {
    "check", "checked", "complete", "next"
};
const int UNIVERSAL_ADVANCE_COUNT = 4;

/*
 * Notes:
 *  - read_clip basenames map to WAV files generated by scripts/make_audio.py
 *    (e.g. "engine_fire_1" -> /spiffs/engine_fire_1.wav).
 *  - advance phrases obey MultiNet rules (letters + spaces only).
 *  - The Emergency Evacuation branch (cabin door vs emergency exit) is flattened:
 *    both exit options are offered at the branch step; saying either advances.
 */
const checklist_t CHECKLISTS[] = {

  { .id="engine_fire", .title="Engine Fire",
    .triggers={"engine fire","fire warning",NULL},
    .item_count=3,
    .items={
      {"engine_fire_1","Throttle affected engine — IDLE",{"idle",NULL}},
      {"engine_fire_2","Engine fire button — LIFT COVER and PUSH",{"push","pushed",NULL}},
      {"engine_fire_3","Illuminated bottle armed button — PUSH",{"push","pushed","armed",NULL}},
    }},

  { .id="takeoff_rejected", .title="Engine Failure/Fire During Takeoff — Below V1 (Rejected)",
    .triggers={"takeoff rejected","abort takeoff","speed below v one",NULL},
    .item_count=3,
    .items={
      {"rej_1","Brakes — AS REQUIRED",{"as required","required",NULL}},
      {"rej_2","Throttles — IDLE",{"idle",NULL}},
      {"rej_3","Speed brakes — EXTEND",{"extend","extended",NULL}},
    }},

  { .id="takeoff_continued", .title="Engine Failure/Fire During Takeoff — Above V1 (Continued)",
    .triggers={"takeoff continued","speed above v one",NULL},
    .item_count=5,
    .items={
      {"cont_1","Maintain directional control",{"control","maintained",NULL}},
      {"cont_2","Accelerate to V R",{"accelerating","rotate speed",NULL}},
      {"cont_3","Rotate at V R, climb at V two",{"rotate","climbing",NULL}},
      {"cont_4","Landing gear — UP after positive rate",{"up","gear up",NULL}},
      {"cont_5","At fifteen hundred feet retract flaps then accelerate",{"flaps up","accelerating",NULL}},
    }},

  { .id="engine_fail_final", .title="Engine Failure During Final Approach",
    .triggers={"engine failure final approach","engine failure approach",NULL},
    .item_count=3,
    .items={
      {"fin_1","Thrust operating engine — INCREASE as required",{"increased","as required",NULL}},
      {"fin_2","Airspeed — V approach",{"v approach","set",NULL}},
      {"fin_3","Flaps — TAKEOFF and APPROACH",{"set","flaps set",NULL}},
    }},

  { .id="emergency_restart", .title="Emergency Restart — Two Engines",
    .triggers={"emergency restart","engine restart","restart engines",NULL},
    .item_count=4,
    .items={
      {"res_1","Ignition switches — BOTH ON",{"both on","on",NULL}},
      {"res_2","Left and right fuel boost switches — BOTH ON",{"both on","on",NULL}},
      {"res_3","Throttles — IDLE",{"idle",NULL}},
      {"res_4","If altitude allows increase airspeed to two hundred knots",{"increased","set",NULL}},
    }},

  { .id="electrical_fire", .title="Electrical Fire or Smoke / Smoke Removal",
    .triggers={"electrical fire","electrical smoke","smoke removal","cabin smoke"},
    .item_count=2,
    .items={
      {"elec_1","Oxygen masks — DON and emergency",{"on","donned","emergency",NULL}},
      {"elec_2","Microphone select switches — mic oxygen mask",{"set","selected",NULL}},
    }},

  { .id="cabin_altitude", .title="Cabin Altitude",
    .triggers={"cabin altitude","cabin alt","depressurization",NULL},
    .item_count=4,
    .items={
      {"cab_1","Oxygen masks — DON and one hundred percent oxygen",{"on","donned",NULL}},
      {"cab_2","Microphone select switches — mic oxygen mask",{"set","selected",NULL}},
      {"cab_3","Emergency descent — AS REQUIRED",{"as required","descending",NULL}},
      {"cab_4","Passenger oxygen — make sure passengers are receiving oxygen",{"confirmed","receiving",NULL}},
    }},

  { .id="emergency_descent", .title="Emergency Descent",
    .triggers={"emergency descent","rapid descent",NULL},
    .item_count=4,
    .items={
      {"des_1","Autopilot trim disconnect — PRESS and RELEASE",{"pressed","released",NULL}},
      {"des_2","Throttles — IDLE",{"idle",NULL}},
      {"des_3","Speed brakes — EXTEND",{"extend","extended",NULL}},
      {"des_4","Pitch attitude — approximately twenty degrees nose down",{"nose down","set",NULL}},
    }},

  { .id="battery_overtemp", .title="Battery Overtemperature",
    .triggers={"battery overtemp","battery overtemperature","batt o temp",NULL},
    .item_count=3,
    .items={
      {"bat_1","Volt amp — NOTE",{"noted","note",NULL}},
      {"bat_2","Battery switch — EMERGENCY",{"emergency","set",NULL}},
      {"bat_3","Volt amp — NOTE decrease",{"noted","decreasing",NULL}},
    }},

  { .id="autopilot_malfunction", .title="Autopilot Malfunction",
    .triggers={"autopilot malfunction","autopilot failure",NULL},
    .item_count=1,
    .items={
      {"ap_1","Autopilot trim disconnect — PRESS and RELEASE",{"pressed","released",NULL}},
    }},

  { .id="trim_runaway", .title="Electric Elevator Trim Runaway",
    .triggers={"trim runaway","elevator trim runaway","elevator trim",NULL},
    .item_count=5,
    .items={
      {"trim_1","Autopilot trim disconnect — PRESS and RELEASE",{"pressed","released",NULL}},
      {"trim_2","Throttles — AS REQUIRED",{"as required","set",NULL}},
      {"trim_3","Speed brakes — AS REQUIRED",{"as required","set",NULL}},
      {"trim_4","Manual elevator trim — AS REQUIRED",{"as required","set",NULL}},
      {"trim_5","Pitch trim circuit breaker left panel — PULL",{"pull","pulled",NULL}},
    }},

  { .id="emergency_evacuation", .title="Emergency Evacuation",
    .triggers={"emergency evacuation","evacuate","evacuation",NULL},
    .item_count=9,
    .items={
      {"evac_1","Parking brake — SET",{"set",NULL}},
      {"evac_2","Throttles — BOTH OFF",{"both off","off",NULL}},
      {"evac_3","Left and right engine fire buttons — BOTH PRESS",{"both press","pressed",NULL}},
      {"evac_4","Bottle armed buttons — BOTH PRESS if fire suspected",{"both press","pressed",NULL}},
      {"evac_5","Battery switch — OFF",{"off",NULL}},
      {"evac_6","E L T — make sure system is activated",{"activated","confirmed",NULL}},
      {"evac_7","Airplane and area — check for best escape route",{"checked","confirmed",NULL}},
      {"evac_8","Exit via cabin door open it, or via emergency exit remove the door",{"cabin door","emergency exit",NULL}},
      {"evac_9","Move away from airplane — procedure complete",{"clear","complete",NULL}},
    }},
};

const int CHECKLIST_COUNT = sizeof(CHECKLISTS) / sizeof(CHECKLISTS[0]);
